#pragma once
#include <iostream>
#include <format>
#include <unordered_map>
#include <memory>
#include <array>
#include <random>

#include "glm.hpp"
#include "glm/gtc/matrix_transform.hpp"
#include "SDL3/SDL.h"
#include "glad/glad.h"
#include "imgui.h"
#include "imgui_impl_sdl3.h"
#include "imgui_impl_opengl3.h"

#include "FactoryMesh.h"
#include "Shader.h"
#include "Model.h"
#include "Camera.h"
#include "Primitive.h"
#include "OBJLoader.h"
#include "UI.h"
#include "LightManager.h"
#include "Collider.h"
#include "MousePicker.h"
#include "Crosshair.h"
#include "FBO.h"
#include "Skybox.h"
#include "UBO.h"
#include "AssimpLoader.h"